# Generated by Django 3.2.6 on 2026-06-16 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedPaymentRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('collected_payments', models.JSONField(default=list)),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('declined_reason', models.TextField(blank=True, null=True)),
                ('payment_medium', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], max_length=15)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='delivery_agents/collected-payments/')),
            ],
            options={
                'verbose_name': 'collected payment register',
                'verbose_name_plural': 'collected payments register',
            },
        ),
        migrations.CreateModel(
            name='CollectPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=128)),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_transferred', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'collected payment',
                'verbose_name_plural': 'collected payments',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAgents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=128)),
                ('phone1', models.CharField(max_length=128)),
                ('phone2', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=256)),
                ('active_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='customers/images/')),
                ('id_proof', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='delivery_agents/proofs/')),
            ],
            options={
                'verbose_name': 'delivery agent',
                'verbose_name_plural': 'delivery agents',
                'db_table': 'delvery_agent_delivery_agent',
                'ordering': ('-date_added', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryAgentTravel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('origin_latitude', models.TextField(blank=True, null=True)),
                ('origin_longitude', models.TextField(blank=True, null=True)),
                ('pickup_latitude', models.TextField(blank=True, null=True)),
                ('pickup_longitude', models.TextField(blank=True, null=True)),
                ('delivery_latitude', models.TextField(blank=True, null=True)),
                ('delivery_longitude', models.TextField(blank=True, null=True)),
                ('pickup_distance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('delivery_distance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pickup_distance_text', models.CharField(max_length=125, null=True)),
                ('delivery_distance_text', models.CharField(max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'delivery agent location',
                'verbose_name_plural': 'delivery agent locations',
                'db_table': 'delvery_agent_travel',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('delivery_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_agent.deliveryagents')),
            ],
            options={
                'verbose_name': 'rating',
                'verbose_name_plural': 'rating',
            },
        ),
    ]
