# Generated by Django 3.2.6 on 2026-06-16 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('delivery_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrating',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='deliveryagenttravel',
            name='delivery_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_agent.deliveryagents'),
        ),
        migrations.AddField(
            model_name='deliveryagenttravel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='deliveryagents',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_deliveryagents_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryagents',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_deliveryagents_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryagents',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
