services:
  - type: web
    name: onaiza
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn onaiza.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    nativePackages:
      - name: libmagic1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DEBUG
        value: "False"
      - key: SERVER
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: onaiza-db
          property: connectionString

databases:
  - name: onaiza-db
    databaseName: onaiza
    plan: free
