# Generated by Django 3.2.6 on 2026-06-16 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoucher',
            name='warehouse',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='account_head',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='finance.accounthead'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='bank',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_paymentvoucher_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='financial_year',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='finance.financialyear'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_paymentvoucher_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='warehouse',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='journalvoucheritem',
            name='account_head',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='finance.accounthead'),
        ),
        migrations.AddField(
            model_name='journalvoucheritem',
            name='journal',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='finance.journalvoucher'),
        ),
        migrations.AddField(
            model_name='journalvoucheritem',
            name='warehouse',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_journalvoucher_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='financial_year',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='finance.financialyear'),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_journalvoucher_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceprefix',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_invoiceprefix_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceprefix',
            name='financial_year',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='finance.financialyear'),
        ),
        migrations.AddField(
            model_name='invoiceprefix',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_invoiceprefix_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_financialyear_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_financialyear_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnotevoucher',
            name='bank',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='debitnotevoucher',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_debitnotevoucher_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnotevoucher',
            name='financial_year',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_debitnotevoucher_objects', to='finance.financialyear'),
        ),
        migrations.AddField(
            model_name='debitnotevoucher',
            name='purchase_return',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchasereturn'),
        ),
        migrations.AddField(
            model_name='debitnotevoucher',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='debitnotevoucher',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_debitnotevoucher_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnotevoucher',
            name='warehouse',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='bank',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_creditnotevoucher_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='financial_year',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_creditnotevoucher_objects', to='finance.financialyear'),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='sale_return',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='sales.salereturn'),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_creditnotevoucher_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnotevoucher',
            name='warehouse',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_bankaccount_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_bankaccount_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='warehouse',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='accountheadopening',
            name='account_head',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='finance.accounthead'),
        ),
        migrations.AddField(
            model_name='accountheadopening',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_accountheadopening_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountheadopening',
            name='financial_year',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_accountheadopening_objects', to='finance.financialyear'),
        ),
        migrations.AddField(
            model_name='accountheadopening',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_accountheadopening_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountheadopening',
            name='warehouse',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='accounthead',
            name='account_group',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='finance.accountgroup'),
        ),
        migrations.AddField(
            model_name='accounthead',
            name='bank_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='accounthead',
            name='creator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_accounthead_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounthead',
            name='updater',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_accounthead_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='creator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_accountgroup_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='updater',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_accountgroup_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
