# Generated by Django 3.2.6 on 2026-06-16 13:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'designation',
                'verbose_name_plural': 'designations',
                'db_table': 'designation',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('leave_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('half_leave_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary', models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'salary_pay',
                'verbose_name_plural': 'salary_pays',
                'db_table': 'salary_pay',
            },
        ),
        migrations.CreateModel(
            name='SalaryAllowance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('allowance_type', models.CharField(choices=[('over time', 'Over Time'), ('working on holiday', 'Working On Holiday')], max_length=128)),
                ('days', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate_per_day', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_paid', models.BooleanField(default=False)),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Salary Allowance',
                'verbose_name_plural': 'Salary Allowances',
                'db_table': 'staff_salary_allowance',
                'ordering': ('-auto_id',),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('staff_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=40)),
                ('staff_role', models.CharField(choices=[('warehouse_manager', 'Warehouse Manager'), ('normal_staff', 'Normal Staff'), ('billing_staff', 'Billing Staff')], default='normal_staff', max_length=40)),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='staffs/photo/', verbose_name='photo')),
                ('address', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('staff_age', models.TextField(blank=True, null=True)),
                ('current_salary', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('branch', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=128, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=128, null=True)),
                ('account_num', models.CharField(blank=True, max_length=128, null=True)),
                ('theme', models.CharField(blank=True, choices=[('teal', 'Teal'), ('blue', 'Blue'), ('bluegrey', 'Blue Grey'), ('cyan-600', 'Cyan'), ('green', 'Green'), ('lightgreen', 'Light Green'), ('purple-400', 'Purple'), ('red-400', 'Red'), ('pink-400', 'Pink'), ('brown', 'Brown'), ('grey-600', 'Grey'), ('orange', 'Orange')], default='teal', max_length=40, null=True)),
                ('is_currently_working', models.BooleanField(default=False)),
                ('normal_staff', models.BooleanField(default=False)),
                ('super_admin', models.BooleanField(default=False)),
                ('client_manager', models.BooleanField(default=False)),
                ('staff_manager', models.BooleanField(default=False)),
                ('advance_salary', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=4, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('debit', models.DecimalField(decimal_places=4, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_staff_objects', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='staffs.designation')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staffs',
                'db_table': 'staff',
                'ordering': ('-auto_id',),
            },
        ),
        migrations.CreateModel(
            name='StaffRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('leave_count', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('half_leave_count', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary', models.DecimalField(decimal_places=0, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('is_partially_paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_staffrecord_objects', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_staffrecord_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Techpe staff record',
                'verbose_name_plural': 'Techpe staff records',
                'db_table': 'techpe_staff_record',
                'ordering': ('staff',),
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('leave_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('half_leave_count', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_present', models.BooleanField(default=False)),
                ('is_leave', models.BooleanField(default=False)),
                ('is_halfday', models.BooleanField(default=False)),
                ('is_excuseleave', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_work_at_home', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_staffattendance_objects', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_staffattendance_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff_attendance',
                'verbose_name_plural': 'staff_attendances',
                'db_table': 'staff_attendence',
            },
        ),
    ]
