# Generated by Django 3.2.6 on 2026-06-16 13:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=128)),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('retail_price', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('whole_sale_price', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'general_batch',
                'verbose_name_plural': 'general_batchs',
                'db_table': 'general_batch',
                'ordering': ('expire_date', 'mrp'),
            },
        ),
        migrations.CreateModel(
            name='ChargePerKilometer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'charge per kilometer',
                'verbose_name_plural': 'charges per kilometer',
                'db_table': 'general_charge_per_kilometer',
            },
        ),
        migrations.CreateModel(
            name='DamagedProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Damaged Product',
                'verbose_name_plural': 'Damaged Products',
                'db_table': 'general_damaged_product',
                'ordering': ('-auto_id',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=128)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Invoice Design',
                'verbose_name_plural': 'Invoice Designs',
                'db_table': 'invoice_design',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'stock_transfer',
                'verbose_name_plural': 'stock_transfers',
                'db_table': 'stock_transfer',
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('retail_price', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('whole_sale_price', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('manufacturing_date', models.DateField()),
                ('expire_date', models.DateField()),
            ],
            options={
                'verbose_name': 'stock_transfer_item',
                'verbose_name_plural': 'stock_transfer_items',
                'db_table': 'stock_transfer_items',
                'ordering': ('auto_id',),
            },
        ),
        migrations.CreateModel(
            name='StockUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=128)),
                ('update_type', models.CharField(choices=[('inward', 'Inward'), ('outward', 'Outward')], default='inward', max_length=128)),
            ],
            options={
                'verbose_name': 'stock_update',
                'verbose_name_plural': 'stock_updates',
                'db_table': 'stock_update',
            },
        ),
        migrations.CreateModel(
            name='StockUpdateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_new_batch', models.BooleanField(default=False)),
                ('batch_number', models.CharField(blank=True, max_length=128, null=True)),
                ('expire_date', models.DateField()),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mrp', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('retail_price', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('whole_sale_price', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.batch')),
            ],
            options={
                'verbose_name': 'stock_update_item',
                'verbose_name_plural': 'stock_update_items',
                'db_table': 'stock_update_item',
            },
        ),
    ]
