# Generated by Django 3.2.6 on 2026-06-16 13:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_type', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], default='b2c', max_length=128)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=128, null=True)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, choices=[('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli ', 'Dadra and Nagar Haveli '), ('Daman and Diu', 'Daman and Diu'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Lakshadweep union territory', 'Lakshadweep union territory'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry union territory', 'Puducherry union territory'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Kerala', max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('opening_type', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=128, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_privilege_points', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('privilege_points', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='customers/images/')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customers_customer',
                'ordering': ('-date_added', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserOtpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=16)),
                ('otp', models.PositiveIntegerField()),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('resend_otp_index', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'OTP Record',
                'verbose_name_plural': 'OTP Records',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('subject', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('solved', 'Solved')], max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/attachment/')),
                ('reject_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_ticket_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_ticket_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'tickets',
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='PrivilegePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_of_point', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('point_gained_online', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('point_gained_offline', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_privilegepoint_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_privilegepoint_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'privilege_point',
                'verbose_name_plural': 'privilege_points',
                'db_table': 'privilege_points',
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('address_type', models.IntegerField(choices=[(10, 'Home'), (20, 'Office')])),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('house_name', models.TextField()),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('landmark', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('is_default', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'customer adress',
                'verbose_name_plural': 'customer addresses',
                'ordering': ('-is_default', 'name'),
            },
        ),
    ]
