# Generated by Django 3.2.6 on 2026-06-16 13:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('finance', '0001_initial'),
        ('delivery_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'Confirmed')], max_length=10)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ('-date_added', 'status'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.PositiveIntegerField(blank=True, choices=[(10, 'Pending'), (20, 'Accepted'), (30, 'Packed'), (40, 'Declined')], default=10, null=True)),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ('qty',),
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_timeslot_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_timeslot_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'time slot',
                'verbose_name_plural': 'time slots',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('billing_name', models.CharField(max_length=50)),
                ('billing_phone', models.CharField(max_length=10)),
                ('billing_address', models.TextField(blank=True, max_length=128, null=True)),
                ('billing_landmark', models.CharField(max_length=128)),
                ('billing_street', models.CharField(max_length=128)),
                ('billing_state', models.CharField(max_length=128)),
                ('billing_city', models.CharField(max_length=128)),
                ('order_status', models.CharField(choices=[('10', 'Pending'), ('20', 'Shipped'), ('30', 'Delivered'), ('40', 'Cancelled')], default=10, max_length=5)),
                ('payment_method', models.CharField(max_length=128)),
                ('payment_status', models.CharField(choices=[('10', 'Pending'), ('20', 'Recieved'), ('30', 'Failed')], max_length=5)),
                ('assigned_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_agent_is_accept', models.BooleanField(blank=True, null=True)),
                ('delivery_agent_declined_reason', models.CharField(blank=True, choices=[('too_long', 'Too Long'), ('time_waste', 'Time Waste'), ('large_order_list', 'Large Order List')], max_length=100, null=True)),
                ('delivery_agent_declined_reason_text', models.TextField(blank=True, null=True)),
                ('pickup_status', models.CharField(blank=True, choices=[('reached', 'Reached Pickup Location'), ('picked_up', 'Picked Up')], max_length=256, null=True)),
                ('total_amt', models.FloatField()),
                ('card_name', models.CharField(blank=True, max_length=128, null=True)),
                ('card_number', models.CharField(blank=True, max_length=128, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('delivery_note', models.TextField(blank=True, null=True)),
                ('order_no', models.IntegerField()),
                ('order_id', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_orders_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('delivery_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_agent.deliveryagents')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.invoiceprefix')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.timeslot')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_orders_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-date_added',),
            },
        ),
    ]
