# Generated by Django 3.2.6 on 2026-06-16 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('sales', '0001_initial'),
        ('products', '0001_initial'),
        ('general', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='warehouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.batch'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_sale_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_voucher',
            field=models.OneToOneField(limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.receiptvoucher'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_prifix',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.invoiceprefix'),
        ),
        migrations.AddField(
            model_name='sale',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_sale_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse'),
        ),
    ]
